import {db} from "@apo/db";
import type {AgentTool} from "./types.js";
import {normalizeVietnamesePhone} from "../customers/phone.js";

export function createAgentTools(pageId:string,conversationId:string,customerPlatformId:string):AgentTool[]{return [
  {name:"get_product_info",description:"Tra cứu thông tin sản phẩm chính xác trước khi trả lời giá, công dụng, khuyến mãi hoặc cách dùng.",parameters:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},execute:async input=>{const query=String(input.query??"").trim();return db.product.findMany({where:{pageId,active:true,OR:[{name:{contains:query,mode:"insensitive"}},{sku:{contains:query,mode:"insensitive"}},{description:{contains:query,mode:"insensitive"}}]},select:{id:true,sku:true,name:true,price:true,promo:true,description:true,usage:true,faq:true,assetGroups:{where:{active:true},select:{id:true,name:true}}},take:10});}},
  {name:"check_customer_history",description:"Kiểm tra dữ liệu khách và đơn cũ trước khi hỏi lại tên, số điện thoại hoặc địa chỉ.",parameters:{type:"object",properties:{},additionalProperties:false},execute:async()=>{const customer=await db.customer.findUnique({where:{pageId_platformCustomerId:{pageId,platformCustomerId:customerPlatformId}},include:{orders:{orderBy:{createdAt:"desc"},take:10}}});return customer??{found:false,conversationId};}},
  {name:"check_order_status",description:"Kiểm tra trạng thái đơn bằng số điện thoại hoặc mã đơn.",parameters:{type:"object",properties:{phone:{type:"string"},orderCode:{type:"string"}},additionalProperties:false},execute:async input=>{const phone=input.phone?normalizeVietnamesePhone(String(input.phone)):null;const code=input.orderCode?String(input.orderCode):undefined;return db.order.findMany({where:{pageId,OR:[...(code?[{code}]:[]),...(phone?[{customer:{phone}}]:[])]},select:{code:true,status:true,shipmentStatus:true,trackingCode:true,total:true,cod:true,items:true,createdAt:true},orderBy:{createdAt:"desc"},take:10});}}
];}
